name: Incorrect Documentation
description: Report an issue with the documentation.
title: "[Incorrect Docs]: "
labels: ["Incorrect Docs"]
body:
  - type: markdown
    attributes:
      value: |-
        For general questions please instead visit our [support server](https://support.mantaro.site).
  - type: textarea
    attributes:
      label: Describe the Documentation Issue
      description: Provide a clear and concise description of the Issue you found.
      placeholder: I found...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Location of the issue
      description: Please provide us with a direct link to the section in which you found the Issue.
      placeholder: https://www.mantaro.site/mantaro-wiki/...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Provide any additional context or words you would like.
      placeholder: I...
    validations:
      required: false