name: Build and deploy documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.head_commit.message == "build" }}

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/mantaro-wiki

      - name: close triggering issue
        uses: actions/github-script@0.9.0
        env:
          GITHUB_RUN_ID: ${{github.run_id}}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'documentation is deployed'
            })
            await github.issues.update({
             issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed'
            })
